### ISSUE TITLE
Make Navbar reappear on scrolling downwards

### ISSUE THREAD

**Issue by kashnx** [gitgoap/AI-Snipping-Tool#33] opened 2024-06-02 20:36 UTC
I can enhance user experience by making navbar disappear on scrolling upwards and reappear in scrolling downwards.

**Comment by gitgoap** [comment] 2024-06-03 08:17
Comment on this issue to get assigned!

**Comment by kashnx** [comment] 2024-06-03 09:15
Please Assign this issue to me.

**Comment by gitgoap** [comment] 2024-06-03 16:52
@kashnx go for it

**Comment by Palakmeena** [comment] 2024-06-04 13:34
please assign this to me

**Comment by gitgoap** [comment] 2024-06-09 16:08
@Palakmeena go for it

**Comment by gitgoap** [comment] 2024-06-13 15:27
@Palakmeena What's the status of the issue?

**Comment by Palakmeena** [comment] 2024-06-13 16:06
The index.html file is not rendering on webpage, can you please help me with it

**Comment by gitgoap** [comment] 2024-06-14 05:47
> The index.html file is not rendering on webpage, can you please help me with it

It's not supposed to render like a webpage because the index.html file is part of the chrome extension so follow the instructions on `readme` and load it as an extension instead of loading it as a webpage.

If you still have problems then contact me on discord.

**Comment by Palakmeena** [comment] 2024-06-14 08:57
okay got it👍

**Comment by gitgoap** [comment] 2024-06-17 06:18
@Palakmeena Any updates

**Comment by Garvanand** [comment] 2024-06-17 08:00
Kindly assign the issue to me I will work on it and try to solve it ASAP @gitgoap

**Comment by Garvanand** [comment] 2024-06-19 07:40
sure, i'll start the work right away

**Comment by Garvanand** [comment] 2024-06-19 10:51
![image](https://github.com/gitgoap/AI-Snipping-Tool/assets/33595457/6699b410-2818-4c22-8d40-0878f7ed1471)
can you share the snippet or short demo video of the navbar not reappearing

**Comment by Garvanand** [comment] 2024-06-19 17:39
![image](https://github.com/gitgoap/AI-Snipping-Tool/assets/33595457/dd3dc319-00b9-485c-aef4-1de4b16f4531)
like this is the issue

**Comment by Garvanand** [comment] 2024-06-19 17:50
@gitgoap kindly review the PR and merge

**Comment by gitgoap** [comment] 2024-06-20 16:30
@Garvanand 
are you working on it?

**Comment by Garvanand** [comment] 2024-06-20 16:38
Yes

**Comment by Garvanand** [comment] 2024-06-20 16:38
Just few more changes to wind it up

**Comment by gitgoap** [comment] 2024-06-28 03:24
@Garvanand 
What's the update on your work?

**Comment by Garvanand** [comment] 2024-06-28 03:48
Everything was done just that ocr text was giving problems I will rectify it as well by today and close the issue

**Comment by Garvanand** [comment] 2024-06-28 03:48
> Everything was done just that ocr text was giving problems I will rectify it as well by today and close the issue

The OCR Text written in heading

**Comment by gitgoap** [comment] 2024-07-05 05:08
@Garvanand give me the updates

**Comment by Garvanand** [comment] 2024-07-05 08:18
Hi,so was a bit occupied due to my exams just that Text part is giving issue rest the disappearance of save and close button is done,give some more time I will figure it out for that text part as well and get back to you with the issue rectified in a day or so.

**Comment by apoorvsxna** [comment] 2024-07-19 13:16
@gitgoap Can you please elaborate what the issue is?
Also, is this issue still present in the current version of the extension?

**Comment by gitgoap** [comment] 2024-07-19 13:45
I think it's not an issue anymore.

**Closed** 2024-07-19 13:46 UTC
Labels: enhancement, intermediate
